[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "datascaler-open-clip"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "calflops>=0.3.2",
    "mup>=1.0.0",
    "open-clip-torch[training]>=2.32.0",
    "pyarrow>=15.0.2",
    "pydantic>=2.11.1",
    "typer>=0.15.2",
    "qpsolvers[osqp]",
    "faiss-cpu",
    "sentence_transformers",
    "addict",
    "yapf",
    "transformers",
    "easyocr",
    "opencv-python",
]

[project.scripts]
datascaler-open-clip = "datascaler_open_clip.cli.main:app"
